export const BLACK                 ='#000'
export const WHITE                 ='#fff'
export const YELLOW                ='#dfa827'
export const GREY_PLACEHOLDER      ='#B3B3B3'
export const DARK_GREEN            ='#0BAE24'
export const BACKGROUND            ='#eee'
export const GRAY                  ='gray'
export const LIGHT_GRAY            ='#ddd'
export const LIGHT_GRAY_2          ='#d5d5d5'
export const DARK_GRAY             ='#444'
export const RED                   ='#F00E0E'
export const BLUE                  ='#1f2839'
export const WARNING               ='#ffc107'
export const ERROR                 ='#177bf2'

